select * from CCustomer;
select * from Inventory;
select * from Sales;

drop table sales;
CREATE TABLE SALES(
SALNUM NUMBER(11),
CUTEL     VARCHAR2(20),
IVNUM	NUMBER(10,0) ,
SCOUNT	NUMBER(3,0),
DDATE       DATE,
PAY     VARCHAR2(10),
CONSTRAINT SALES_PK_SALNUM PRIMARY KEY (SALNUM),
CONSTRAINT SALES_FK_CUTEL FOREIGN KEY (IVNUM) REFERENCES INVENTORY (IVNUM),
CONSTRAINT SALES_FK_PCOUNT FOREIGN KEY (CUTEL) REFERENCES CCUSTOMER (CUTEL));

CREATE SEQUENCE SEQ_SALNUM; 

--INSERT INTO Sales(SALNUM,  IVNUM,SCOUNT, DDATE) 
-- VALUES(SEQ_SALNUM.nextval, (SELECT ivnum FROM Inventory WHERE pname='아메리카노' ),1,SYSDATE);


UPDATE INVENTORY SET  PCOUNT=PCOUNT+9
WHERE IVNUM=(SELECT ivnum FROM Inventory WHERE pname='아메리카노');
SELECT ivnum FROM Inventory WHERE pname='아메리카노';

			